name: Create and publish a docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: phpfpm
  REPO: docker-compose-php-stack

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ env.REGISTRY }}/phpfpm
      #     tags: |
      #       type=ref,event=branch
      #       type=sha

      # - name: Build and push Docker image
      #   run: |
      #     docker compose -f docker-compose.yml build ${{ env.IMAGE_NAME }}
      #     docker push ${{ env.IMAGE_NAME }}
      - name: Docker-compose action
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: ${{ env.IMAGE_NAME }}

      # - name: push Docker image
      #   run: docker compose push ${{ env.IMAGE_NAME }}
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: '0.2.6-rc.1' # optional
          docker_compose: 'docker-compose.build.yml' # required
          repo_token: "${{ secrets.TOKEN }}"